spring:
  application:
    name: daybreak
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL JDBC 드라이버 클래스 이름
    url: ${DB_URL} # jdbc:mysql://localhost:3306/{데이터베이스명}
    username: ${DB_USER} # MySQL 유저 이름
    password: ${DB_PW} # MySQL 비밀번호
  jpa:
    database: mysql # 사용할 데이터베이스 유형 지정 (MySQL)
    database-platform: org.hibernate.dialect.MySQLDialect # Hibernate에서 사용할 MySQL 방언(dialect) 설정
    show-sql: true # 실행된 SQL 쿼리를 콘솔에 출력할지 여부 설정
    hibernate:
      ddl-auto: none # 애플리케이션 실행 시 데이터베이스 스키마의 상태를 설정
    properties:
      hibernate:
        format_sql: true # 출력되는 SQL 쿼리를 보기 좋게 포맷팅

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${REST_API_KEY}
            client-secret: ""
            scope: profile_nickname
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


openai:
  model: gpt-4o-mini
  api:
    key: ${OPENAI_API_KEY}   # 환경변수에서 주입

upstage.api-key: ${UPSTAGE_API_KEY}


kakao:
  client_id: ${REST_API_KEY}
  redirect_uri: ${KAKAO_REDIRECT_URI}


logging:
  level:
    umc9th_hackathon.daybreak.global.config: DEBUG
    org.springframework.security.oauth2: DEBUG

server:
  base-url: ${SERVER_BASE_URL:http://localhost:8080}